#@@@@@@@@@@@@@@@
# some useful cmds:
# dnscrypt-proxy -check -config <PATH>/dnscrypt-proxy.toml
# systemctl -o cat -fu dnscrypt-proxy 
# systemctl <start/status/restart> dnscrypt-proxy
#@@@@@@@@@@@@@@@


#server_names = ['']   #if commented out,it means wildcard
#disabled_server_names = ['']

odoh_servers = true
doh_servers = false
dnscrypt_servers = false

ipv4_servers = true
ipv6_servers = false

#Commented out for fail-safe reasons, and manually chose servers in anonymized_dns routes. 
#require_dnssec = true
#require_nolog = true
#require_nofilter = false

ignore_system_dns = true
bootstrap_resolvers = ['8.8.8.8:53'] #reason: DNS resolve the host from where servers are downloaded and DNS servers before use, unused if cached
netprobe_address = '8.8.8.8:53' #reason: internet connectivity check
netprobe_timeout = 5

cache = true
cache_size = 256

enable_hot_reload = true

[anonymized_dns] #necessary for ODoH servers to work 
routes = [{server_name = 'odoh-crypto-sx', via = ['odohrelay-ibksturm', 'odohrelay-ams', 'odohrelay-se']},
{server_name = 'odoh-cloudflare', via = ['*']},
{server_name = '*', via = ['*']}
]
skip_incompatible = true

[sources]
[sources.odoh-servers]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md']#,'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = '/tmp/odoh-servers.md'
#prefix = ''

[sources.odoh-relays]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md'] #,'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = '/tmp/odoh-relays.md'
#prefix = ''

[monitoring_ui]
enabled = true
listen_address = "127.0.0.1:8080"
username = "<user>" #replace 
password = "<pass>" #replace
tls_certificate = ""
tls_key = ""
enable_query_log = true
privacy_level = 0   #0-2
