#@@@@@@@@@@@@@@@
# some useful cmds:
# dnscrypt-proxy -check -config <PATH>/dnscrypt-proxy.toml
# systemctl -o cat -fu dnscrypt-proxy 
# systemctl <start/status/restart> dnscrypt-proxy
#@@@@@@@@@@@@@@@


#server_names = ['']   #if commented out,it means *
#disabled_server_names = ['']

## listen only to localhost IPv4/6 adresses   ['127.0.0.1:53', '[::1]:53']
## listen to all IPv4/6 addresses ['0.0.0.0:53', '[::]:53']
listen_addresses = ['127.0.0.1:53']
max_clients = 12

# user_name = 'user'

ipv4_servers = true
ipv6_servers = false

dnscrypt_servers = false
doh_servers = false
odoh_servers = true

#Commented out for fail-safe reasons, and manually chose servers in anonymized_dns routes. 
#require_dnssec = true
#require_nolog = true
#require_nofilter = false


force_tcp = false
http3 = false
http3_probe = false

# proxy = 'socks5://dnscrypt:dnscrypt@127.0.0.1:9050'
#http_proxy = 'http://127.0.0.1:8888'

timeout = 5000
keepalive = 30

# edns_client_subnet = ['0.0.0.0/0', '2001:db8::/32']
# blocked_query_response = 'refused'

lb_strategy = 'wp2'
lb_estimator = true
enable_hot_reload = true


log_level = 2
## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

log_file = '/tmp/dnscrypt-proxy.log'
log_file_latest = false
use_syslog = true
log_files_max_size = 0
log_files_max_age = 7
log_files_max_backups = 0

cert_refresh_concurrency = 10
cert_refresh_delay = 5
cert_ignore_timestamp = false

dnscrypt_ephemeral_keys = true

tls_disable_session_tickets = true
## 49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
## 49195 = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
## 52392 = TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
## 52393 = TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
#tls_cipher_suite = [49195, 52393, 49199,52392]
#tls_key_log_file = '/dev/null'

ignore_system_dns = true
bootstrap_resolvers = ['8.8.8.8:53'] #reason: DNS resolve the host from where servers are downloaded and DNS servers before use, unused if cached
netprobe_address = '8.8.8.8:53' #reason: internet connectivity check
netprobe_timeout = 5


# offline_mode = false
# query_meta = ['key1:value1', 'key2:value2', 'token:MySecretToken']


block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 10

# forwarding_rules = '/etc/dnscrypt-proxy/forwarding-rules.txt'
# cloaking_rules = '/etc/dnscrypt-proxy/cloaking-rules.txt'
# cloak_ttl = 600
# cloak_ptr = false

cache = true
cache_size = 256
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600



[captive_portals]
# map_file = '/etc/dnscrypt-proxy/captive-portals.txt'



[local_doh]
# listen_addresses = ['127.0.0.1:3000']
# path = '/dns-query'
# cert_file = "/<PATH>/localhost.pem"
# cert_key_file = "/<PATH>/localhost.pem"



[query_log]
file = '/tmp/query.log'
format = 'tsv'
# ignored_qtypes = ['DNSKEY', 'NS']



[nx_log]
file = '/tmp/nx.log'
format = 'tsv'



[blocked_names]
blocked_names_file = '/etc/dnscrypt-proxy/blocked-names.txt'
log_file = '/tmp/blocked-names.log'
log_format = 'tsv'



[blocked_ips]
blocked_ips_file = '/etc/dnscrypt-proxy/blocked-ips.txt'
log_file = '/tmp/blocked-ips.log'
log_format = 'tsv'
[allowed_names]
# allowed_names_file = '/etc/dnscrypt-proxy/allowed-names.txt'
# log_file = '/tmp/dnscrypt-proxy/allowed-names.log'
# log_format = 'tsv'



[allowed_ips]
# allowed_ips_file = '/etc/dnscrypt-proxy/allowed-ips.txt'
# log_file = '/tmp/dnscrypt-proxy/allowed-ips.log'
# log_format = 'tsv'
## {after='21:00', before= '7:00'} matches 0:00-7:00 and 21:00-0:00
## {after= '9:00', before='18:00'} matches 9:00-18:00



[schedules]
# [schedules.time-to-sleep]
#   mon = [{after='21:00', before='7:00'}]
#   tue = [{after='21:00', before='7:00'}]
#   wed = [{after='21:00', before='7:00'}]
#   thu = [{after='21:00', before='7:00'}]
#   fri = [{after='23:00', before='7:00'}]
#   sat = [{after='23:00', before='7:00'}]
#   sun = [{after='21:00', before='7:00'}]
# [schedules.work]
#   mon = [{after='9:00', before='18:00'}]
#   tue = [{after='9:00', before='18:00'}]
#   wed = [{after='9:00', before='18:00'}]
#   thu = [{after='9:00', before='18:00'}]
#   fri = [{after='9:00', before='17:00'}]
## `refreshed_delay` must be in the [24..168] interval.



[broken_implementations]
fragments_blocked = []



[doh_client_x509_auth]
# creds = [
#    { server_name='*', client_cert='client.crt', client_key='client.key' }
# ]




[anonymized_dns] #necessary for ODoH servers to work 
routes = [{server_name = 'odoh-crypto-sx', via = ['odohrelay-ibksturm', 'odohrelay-ams', 'odohrelay-se']},
		  {server_name = 'odoh-cloudflare', via = ['*']},
		  {server_name = '*', via = ['*']}
]
skip_incompatible = true
direct_cert_fallback = false


[sources]
[sources.odoh-servers]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md']#,'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = '/tmp/odoh-servers.md'
#prefix = ''

[sources.odoh-relays]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md'] #,'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = '/tmp/odoh-relays.md'
refresh_delay = 60
#prefix = ''

#[sources.public-resolvers]
#urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md'] #, 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
#cache_file = '/tmp/public-resolvers.md'
#minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#refresh_delay = 60
#prefix = ''

#[sources.relays]
#urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md']#, 'https://download.dnscrypt.info/resolvers-list/v3/relays.md'
#cache_file = '/tmp/relays.md'
#minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#refresh_delay = 60
#prefix = ''

#[sources.quad9-resolvers]
#urls = ['https://www.quad9.net/quad9-resolvers.md']
#minisign_key = 'RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN'
#cache_file = '/tmp/quad9-resolvers.md'
#refresh_delay = 60
#prefix = 'quad9-'

#[sources.parental-control]
#urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/parental-control.md']#, 'https://download.dnscrypt.info/resolvers-list/v3/parental-control.md']
#cache_file = '/tmp/parental-control.md'
#minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#refresh_delay = 120
#prefix = ''

#[sources.dnscry-pt-resolvers]
#urls = ['https://www.dnscry.pt/resolvers.md']
#minisign_key = 'RWQM31Nwkqh01x88SvrBL8djp1NH56Rb4mKLHz16K7qsXgEomnDv6ziQ'
#cache_file = '/tmp/dnscry.pt-resolvers.md'
#refresh_delay = 60
#prefix = 'dnscry.pt-'

#[sources.opennic]
#urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/opennic.md']#, 'https://download.dnscrypt.info/resolvers-list/v3/opennic.md']
#minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#cache_file = '/tmp/opennic.md'
#refresh_delay = 60
#prefix = ''

#[sources.onion-services] #unaccessible without Tor
#urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/onion-services.md', 'https://download.dnscrypt.info/resolvers-list/v3/onion-services.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/onion-services.md']
#minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#cache_file = '/tmp/onion-services.md'
#refresh_delay = 60
#prefix = ''



[dns64]
# prefix = ['64:ff9b::/96']
# resolver = ['[2606:4700:4700::64]:53', '[2001:4860:4860::64]:53']



[monitoring_ui]
enabled = true
listen_address = "127.0.0.1:8080"
username = "toripo"    #replace 
password = "dossantos" #replace
tls_certificate = ""
tls_key = ""
enable_query_log = true
privacy_level = 0
## 0: show all details including client IPs
## 1: anonymize client IPs (default)
## 2: aggregate data only (no individual queries or domains shown)

max_query_log_entries = 100
max_memory_mb = 1
prometheus_enabled = true
prometheus_path = "/m3tr1cs"



[static]  #to generate DNS stamps online: https://dnscrypt.info/stamps/
# [static.myserver]
#   stamp = 'sdns://AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'
